version: "3.9"

services:
  flaskapp:
    image: python:3.12-alpine
    container_name: hugo-flaskapp
    working_dir: /app
    command: >-
      sh -c "apk add --no-cache docker-cli docker-cli-compose && \
      pip install --no-cache-dir flask werkzeug gunicorn && \
      gunicorn -b 0.0.0.0:5050 flask_app.app:app"
    volumes:
      - "/home/jalcocert/Desktop/IT/hugo-theme-gallery-flasked:/app"
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "5050:5050"
    depends_on:
      - hugo-server
    restart: "no"

  # Hugo dev server (live reload) using your prebuilt image
  hugo-server:
    image: hugo_gallery
    container_name: hugo_container
    working_dir: /hugo-theme-gallery/exampleSite
    command: hugo server --bind 0.0.0.0 --port 1318 --baseURL http://localhost:1318/
    ports:
      - "1318:1318"
    volumes:
      - "/home/jalcocert/Desktop/IT/hugo-theme-gallery-flasked:/hugo-theme-gallery"
    restart: "no"

  static-python:
    image: python:3.12-alpine
    container_name: hugo-static-python
    working_dir: /app
    command: python3 -m http.server 4323 --directory /app/public
    volumes:
      - "/home/jalcocert/Desktop/IT/hugo-theme-gallery-flasked/exampleSite/public:/app/public:ro"
    ports:
      - "8089:4323"
    restart: "no"
