#https://github.com/JAlcocerT/Docker/tree/main/Web/SSGs/Hugo

## MAKE SURE YOU RUN THE SITE BUILD COMMAND FIRST, BEFORE DEPLOYING THIS CONTAINER ##
## YOU NEED TO MOUNT THE SITE DURING THE HUGO DEPLOYMENT ##

#version: '3.8'
services:
  server:
    image: klakegg/hugo:0.101.0
    container_name: hugo
    #command: server
    command: server --bind 0.0.0.0 --port 1313 --baseURL http://192.168.1.8/ # Adjust baseURL    
    ports:
      - "1313:1313"
    volumes:
      - "/home/jalcocert/Desktop/IT/hugo-theme-gallery-flasked/:/src" #mount your site here after you've created a new site!